def nav():
    import base64
    from pathlib import Path
    import streamlit as st
    import streamlit.components.v1 as components

    def img_to_bytes(img_path):
        img_bytes = Path(img_path).read_bytes()
        encoded = base64.b64encode(img_bytes).decode()
        return encoded

    hide_streamlit_style = """
            <style>
            .stDeployButton {visibility: hidden;}
            [data-testid="element-container"]:nth-child(2) { 
                display: none !important; 
            }
            </style>
            """
    st.markdown(hide_streamlit_style, unsafe_allow_html=True)

    enter_search_js = """
    <script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function() {
        const doc = window.parent.document // break out of the IFrame
        const inputElement = doc.querySelector("input[aria-label='Please input search content']");

        inputElement.addEventListener("keypress", function(e) {
            if (e.key === "Enter") {
                doc.querySelector(".stButton button").click();
            }
        });

        const searchButton = doc.querySelector(".stButton button");
        searchButton.addEventListener("click", function() {
            const query = doc.querySelector(".stTextInput input").value;
            const searchEngine = doc.querySelectorAll('[data-baseweb="select"]')[1].innerText.trim();

            let url;
            if (searchEngine === "Google") {
                url = `https://www.google.com/search?q=${query}`;
            } else if (searchEngine === "Bing") {
                url = `https://www.bing.com/search?q=${query}`;
            } else if (searchEngine === "Baidu") {
                url = `https://www.baidu.com/s?wd=${query}`;
            } else {
                alert("Please select a search engine");
                return;
            }

            window.open(url, "_blank");
        });
    });
    </script>
    """
    components.html(enter_search_js, height=0)

    st.title("Sim Nav Page")

    search_query = st.text_input("Please input search content")
    search_engine = st.selectbox("Please select a search engine", ("Google", "Bing", "Baidu"))

    if st.button("Search"):
        pass  # This space intentionally left blank, as the search is handled by JavaScript

    tab1, tab2= st.tabs(["🎞 Entertainment", "💊 Mail"])

    with tab1:
        cols = st.columns(8)
        col_list = list(cols)
        with col_list[0]:
            st.write("[Github](https://github.com/)")
        with col_list[1]:
            st.write("[Gitee](https://gitee.com/)")
        with col_list[2]:
            st.write("[Bilibili](https://www.bilibili.com/)")
        with col_list[3]:
            st.write("[Cnblogs](https://www.cnblogs.com/)")

    with tab2:
        cols = st.columns(8)
        col_list = list(cols)
        with col_list[0]:
            st.write("[126 Mail](https://mail.126.com/)")
        with col_list[1]:
            st.write("[163 Mail](https://mail.163.com/)")
        with col_list[2]:
            st.write("[Gmail](https://mail.google.com/)")
        with col_list[3]:
            st.write("[Outlook](https://outlook.live.com/mail/)")
    
    st.sidebar.markdown('''[<img src='data:image/png;base64,{}' class='img-fluid' width=100 height=65>](https://streamlit.io/)'''.format(img_to_bytes("./nav_page/nav_celue.png")), unsafe_allow_html=True)
    st.sidebar.markdown('## Sim Nav Page')

    st.sidebar.markdown('''
    <small>Summary of the [docs](https://docs.streamlit.io/), as of [Streamlit v1.29.0](https://www.streamlit.io/).</small>
    ''', unsafe_allow_html=True)

    st.sidebar.markdown('## About')
    st.sidebar.markdown('Sim-Nav-Page is a page generated by streamlit, a lightweight navigation page can be deployed on a server.')

    st.sidebar.markdown('## Deploy')
    st.sidebar.markdown('You can run it in server, then listen the 8051 port through ngnix server')

    st.sidebar.markdown('''<hr>''', unsafe_allow_html=True)
    st.sidebar.markdown('''<small>[Simple Nav Page v1.0](https://github.com/CallmeLins/streamlit-nav-page)  | Aug 2023 | [CallmeLins](https://CallmeLins.github.io/)</small>''', unsafe_allow_html=True)
